# Generated by Django 5.2.7 on 2025-10-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_room'),
        ('hotels', '0002_remove_room_amenities_remove_room_hotel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
